### ISSUE TITLE
Confirming validity of wrapped documents.

### ISSUE THREAD

**Issue by Meuko** [Open-Attestation/open-attestation#132]
Hi there,
I'm currently trying to validate two different JSON objects ( one containing a **raw certificate** and the other the same certificate, **but wrapped** ) using the function below, but it always returns true for some reason; regardless of whether or not the document is wrapped. Am I misunderstanding this function's intended use? 

https://github.com/Open-Attestation/open-attestation/blob/e4219564a0eae4efe0f18445cb83bcc0acde0f19/src/utils/utils.ts#L70

**Comment by Nebulis** [comment]
You are right and the implementation is wrong. Currently the implement will return true for any document that is not does not have the v3 schema. This is wrong and the following checks should be performed:
- there is a signature with target hash, merkle root and type
- there is a data property which is an object

I'm pretty sure I did that somewhere, I will need to find it or implement it here again. If you are interested for contributing let me know I can guide you

**Comment by Meuko** [comment]
If I have time left this week I'll push a pr, thanks for the information.

**Comment by Nebulis** [comment]
available in v5
