### ISSUE TITLE
Generics for signDocument

### ISSUE THREAD

**Issue by yehjxraymond** [Open-Attestation/open-attestation#136]
![image](https://user-images.githubusercontent.com/7406870/101332203-f1143e00-38af-11eb-8b3b-430170b96044.png)

Current signDocument changes the type to a generic `Promise<SignedWrappedDocument<v2.OpenAttestationDocument>>`, add in generic to automatically update the type of output.

**Comment by Nebulis** [comment]
wrong repo ? https://github.com/Open-Attestation/oa-did-sign/blob/master/src/signDocument/signDocument.ts

This could work:
```
export const signDocument = async (
  document: SignedWrappedDocument<T extends v2.OpenAttestationDocument> | WrappedDocument<T extends v2.OpenAttestationDocument>,
  algorithm: string,
  publicKey: string,
  privateKey: string
): Promise<SignedWrappedDocument<T>>
```

**Comment by yehjxraymond** [comment]
Added in https://github.com/Open-Attestation/oa-did-sign/pull/1/files

Thanks!
