### ISSUE TITLE
BUG: broken dependency, can't resolve rdf-canonize-native in webpack build.

### ISSUE THREAD

**Issue by Neketek** [Open-Attestation/open-attestation#164]
![image](https://user-images.githubusercontent.com/6703760/115264574-173fc980-a13f-11eb-8aa7-d20f24647d3b.png)

Hi, I noticed this problem a long ago, but I thought that it was caused by an old dependency and that by this moment it is going to be fixed. But it's not, therefore, here I am, writing this issue. 

As far as I understand, the situation here is pretty simple. Your code uses ```jsonld``` which uses ```rdf-canonize``` which uses ```rdf-canonize-native```.  Judging by the issues I've read at ```rdf-canonize``` project, ```rdf-canonize-native``` broke several months ago, therefore, the devs decided to simply exclude it from ```rdf-canonize``` deps.  

The strange solution, but apparently, ```rdf-canonize-native``` is an optional dependency, therefore, it doesn't completely break everything, but causes this very suspicious message to appear each time my project starts without ```rdf-canonize-native```: ```"WARNING: Missing strong random number source"```. So, I guess, you can understand why I'm concerned, and I think that you should probably be concerned too. 

If you say, that this isn't a critical issue, I'll be ok with that, but I still suggest you should try to upgrade ```jsonld``` to version 5. Maybe they fixed this obvious problem in the latest version.

**Comment by Nebulis** [comment]
Hi, thanks for the report

SO far we use jsonld only on OA v3, which is in beta. So no critical issue.

Try t upgrade to 5.1.2, it uses json ld v4, maybe it fixes the issue, Otherwise we can try to upgrade to jsonld v5

**Comment by Neketek** [comment]
![image](https://user-images.githubusercontent.com/6703760/115398588-fbe0c700-a1ef-11eb-9575-09f2b1c2c03b.png)
@Nebulis Thanks for the quick response.  Tested your suggestions as soon as I got a chance. So, as a result of the upgrade, the previous error message didn't go away, but a new one appeared, but as far as it doesn't affect v2 functionality I'm fine with that.
