### ISSUE TITLE
BUG: ESM imports not working

### ISSUE THREAD

**Issue by Neketek** [Open-Attestation/open-attestation#195]
Version 6.0.0 package.json is missing the "main" key which prevents the library from being imported. It was in package.json before, I assume it's being missing is just a typo. 

Nothing else to add, pretty straightforward to fix.

**Comment by Nebulis** [comment]
It was not a typo, I wanted to upgrade to a full ESM library, but I currently face many issues. Please stick with 5 in the meantime

**Comment by Neketek** [comment]
> It was not a typo, I wanted to upgrade to a full ESM library, but I currently face many issues. Please stick with 5 in the meantime

@Nebulis 
Ye, thank you. I was just going to post about this, but you did it first.  Is there any way to make v6 work in typescript? Because as  I understood ESM is not really supported, at least now according to the state of this [issue](https://github.com/Open-Attestation/open-attestation/issues/195#issuecomment-893266431).

**Comment by Nebulis** [comment]
Your link goes to the current issue.

I faced issues with node, ts-node and jest. I'm investigating because I want to share ea full report on the attempt for our team.

I will probably fix the v6 beginning of next week. (Mostly a full revert)

**Comment by Neketek** [comment]
> Your link goes to the current issue.
> 
> I faced issues with node, ts-node and jest. I'm investigating because I want to share ea full report on the attempt for our team.
> 
> I will probably fix the v6 beginning of next week. (Mostly a full revert)

Ye, sorry, I've updated the link. Thanks for the info, it's very useful for planning a course of action.

**Comment by Nebulis** [comment]
Your link is interesting. I didn't have any issues with importing OA from a different TS library. And some people said it's working for them too (for instance https://github.com/microsoft/TypeScript/issues/33079#issuecomment-872431024)

For the record, what issue do you currently face?

**Comment by Neketek** [comment]
@Nebulis So, the issue is simple, it's unable to resolve the module in jest and in webpack. According to my linters and autocompletion engine everything is alright. And it's right because the module is in place.  I've tried to switch target and module to es2020, but It didn't help.

**Comment by Nebulis** [comment]
Ok you have the same issue that I found. It's because jest doesn't support ESM (https://github.com/facebook/jest/issues/9771, https://github.com/facebook/jest/issues/9430).

I made it work without typescript, I need to try with TS.

I haven't tested webpack, but I thought it was supported. Now I need to try ... :)

**Comment by Neketek** [comment]
![image](https://user-images.githubusercontent.com/6703760/128691470-c72f4ad6-7095-453f-ade6-3013f771b0f1.png)
@Nebulis 
And here is what I get when I'm trying to build using webpack. Webpack itself doesn't specify anything special to be done in order to work with ESM modules, so I think it might be related to how you reference modules inside of the package.

**Comment by Nebulis** [comment]
It actually looks like the second error I faced. Unlike node resolve mechanism, ESM does not by default resolve dir by loading index.js, or resolve the extension.

For instance with node, you need https://nodejs.org/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm (an experimental flag) and TS doesn't provide a way to generate the correct full path. TS answers is: `developers must provide the correct expected full path, ie in your code you should have something like: import "./3.0/digest/index.js"`. Yes according to TS dev, you mus import JS files in your TS code :)

**Comment by Neketek** [comment]
@Nebulis 
I've made it work with webpack, and probably found the reason why it didn't work initially.
![image](https://user-images.githubusercontent.com/6703760/129004686-00d118cd-1e54-42b9-a8fd-beb49887409a.png)
As far as I understand, according to [this comment](https://github.com/webpack/webpack/issues/11467#issuecomment-769487234) you really need to change how you reference your code inside the package for it to be ESM compliant. So apparently, the new standard requires imports to use fully specified names.  Maybe,  if you change this it will start working with jest and ts without additional tweaking.

**Comment by Nebulis** [comment]
You are correct for the webpack config (I did the same) and the full path. Having correct full path help to solve most of the issues indeed.
