### ISSUE TITLE
as a developer, I want to understand how v3 wrapping works, and how is it different from v2?

### ISSUE THREAD

**Issue by cavacado** [Open-Attestation/open-attestation#207]
- differences between v2 wrap and v3 wrap
- asynchronous or not

**Comment by cavacado** [comment]
top level differences:
- v2 is synchronous, v3 is asynchronous.
- v2 does not follow w3c VC standards so it does not need to validate the data is VC compliant.
- v3 follows w3c VC standards so it does need to validate the data
- how it does so is by calling expand on the derived contexts from @govtech/json-ld library.
- after expanding, it will perform a series of checks to ensure whether the data conforms to the expanded schema

**Comment by Nebulis** [comment]
should we move this to the doc section?

**Comment by cavacado** [comment]
moved into readme, closing
