### ISSUE TITLE
Any Contact address?

### ISSUE THREAD

**Issue by hrik2001** [Open-Attestation/open-attestation#237]
Pardon me for opening an issue that is not directly related to open-attestation.

In the website of open-attestation, and in the github, I couldn't find any method to contact you folks. Moreover, it would be useful if there is some public chat (like IRC or discord or slack or even gitter), which one can join, to contribute in this open source or for other queries.

Thank You

**Comment by cavacado** [comment]
Hey @hrik2001, we do have an official contact address: openattestation_support@tech.gov.sg.
But for better exposure, please do file issues or start a discussion within the github repo itself.
