### ISSUE TITLE
Schema for v2 failing on https://www.jsonschemavalidator.net/

### ISSUE THREAD

**Issue by yehjxraymond** [Open-Attestation/open-attestation#71]
![image](https://user-images.githubusercontent.com/7406870/74310197-9309ed80-4da7-11ea-87df-62ae46ce1958.png)

**Comment by Nebulis** [comment]
It works if you use Schema Draft v6 / v7 (and many other)

**Comment by Nebulis** [comment]
The issue is the $id property => if you remove it or change to URI it's ok

https://json-schema.org/understanding-json-schema/structuring.html#the-id-property

:man_shrugging:

**Comment by Nebulis** [comment]
#77
